-- ユーザーテーブル
CREATE TABLE IF NOT EXISTS users
(
    id         CHAR(36) PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    email      VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
