name: Replace project_template with Repository Name

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [replace_project_template]

permissions:
  contents: write

jobs:
  replace-template:
    runs-on: ubuntu-latest

    if: github.repository != 'Daichi0914/project_template'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Replace project_template safely
        run: |
          echo "Replacing project_template with ${REPO_NAME}"

          find . \
            -type f \
            ! -path "./.git/*" \
            ! -name "*.png" \
            ! -name "*.jpg" \
            ! -name "*.jpeg" \
            ! -name "*.gif" \
            ! -name "*.pdf" \
            ! -name "*.zip" \
            | while read file; do
              if file "$file" | grep -q text; then
                echo "Replacing in $file"
                perl -pi -e "s/project_template/${REPO_NAME}/g" "$file"
              else
                echo "Skipping binary file $file"
              fi
            done

      - name: Delete self workflow
        run: |
          echo "Deleting this workflow file..."
          rm -f .github/workflows/replace_project_template.yml

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Replace 'project_template' with repository name '${REPO_NAME} and delete self workflow'"
          git push
